### PR TITLE
March Pull Request

### PR DESCRIPTION
**Pull request by kirk-sayre-work**

### CODE REVIEW

**Comment by kirk-sayre-work** [comment]
I'll work on adding the MS grammar comments back in, with a MS-GRAMMAR: tag at the start of each comment line to make it clear that the comments are grammar documentation and not commented out pyparsing lines. I'll also add back in the changelog comment sections (I tend to rely on Git logs to track changes, which is why I deleted those comment blocks).

**Comment by decalage2** [comment]
I agree that the changelogs I had in the code were not very useful. No need to put them back, I'll add a global changelog file. I like to track the main changes in each version (for me and end-users), usually git logs are too detailed for that.

**Comment by kirk-sayre-work** [comment]
I added the MS grammar comments back in my most recent commit. Are you adding the global change log file or should I do it? If you want me to do it, where would you like the change log file to go?

**Comment by decalage2** [comment]
Thanks again for all this great work. :-)

I'll take care of the changelog, no need to do it. For now it's mostly in the readme, I'll move the information to a separate file later.

**Pull request merged**
