### PR TITLE
Added API interface, unit tests, and deobfuscation utility

### PR DESCRIPTION
**Pull request by DC3-DCCI**
The following pull request includes a number of features that we have developed internally and would
like to contribute back upstream.

This pull request includes the following:
- API for parsing and evaluating portions of VBA code in an on-demand matter. (#54)
- Added a deobfuscation utility that can be used by itself to clean up code or within the emulation
    to help speed up processing.
- Added documentation for using the API and deobfuscation utility.
- Added unit testing for API, deobfuscation utility, some call expressions, and for a few bug fixes. (#11)
- Added a few modifications to help speed up parsing:
    - Combined operators that have the same operator order level.
    - Converted some grammars to regex. (#4)
- Reorganized some of the complex grammars to make them more readable and easier to update.

### CODE REVIEW

**Comment by decalage2** [comment]
Thanks a lot, this is a great contribution!
I need to check with Kirk Sayre's fork (https://github.com/kirk-sayre-work/ViperMonkey) if there are any conflicts, because he made quite a few commits since I synced the main repo.

Also, is there a specific reason why you chose the regex package instead of re?

**Comment by DC3-DCCI** [comment]
Thanks. I checked and there will be a small merge conflict with Kirk Sayre's work.

The `open_files` and `closed_files` attributes in the Context object were changed to be a dictionary mapping the resolved file path to a byte string (instead of containing separate "name" and "content" fields). This was made possible by allowing the file numbers prefixed with "#" to be stored as a variable in the context, allowing the unique file path to also act as the identifier. This change seemed appropriate since it made for a better API and helped to simplify a lot of code. The other conflicts are trivial.

The regex library was chosen over Python's builtin re library because of its ability to extract all captured groups from a match (instead of just the last one). This helped with the implementation of the deobuscation utility.

**Comment by DC3-DCCI** [comment]
We have rebased the commit to handle the merge conflicts caused by Kirk's branch. Please let us know if you have any questions.

**Comment by decalage2** [comment]
I am trying to install regex on pypy 2 (on Windows) using pip, but it requires compilation... :-(
```
Installing collected packages: regex
  Running setup.py install for regex ... error
[...]
    running build_ext
    building 'regex._regex' extension
    error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```
So I installed Visual C++ for Python, as suggested by the error messages from pip, but then I get this:
```
    C:\Users\x\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\PyPy2\include /Tcregex_2\_regex.c /Fobuild\temp.win32-2.7\Release\regex_2\_regex.obj
    _regex.c
    regex_2\_regex.c(9353) : fatal error C1189: #error :  "Needs to be a wide build."
    error: command 'C:\\Users\\x\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

**Comment by decalage2** [comment]
Do you manage to run ViperMonkey with regex on PyPy? 

It looks like regex may have some issues with PyPy, not sure they are solved: https://bitbucket.org/mrabarnett/mrab-regex/issues/145/1-fail-in-testsuite-under-pypy

If ViperMonkey does not run on PyPy, that's a major issue for performance...

**Comment by decalage2** [comment]
I reported the issue to the regex maintainer, and it has been fixed in a new version of regex on PyPI:

https://bitbucket.org/mrabarnett/mrab-regex/issues/333/error-when-installing-regex-on-pypy27-v711

**Pull request merged**
